# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ee4b46690096a6b711bf7a107edc960d946a510c54be9123be79fe778adfab8d2d901b2f594e9f8a4d51b3a35ec5b38673373b8439840a9497c7ba72c8cd01

test:
  secret_key_base: 6f30382e0b53bbec907d086b386ad3134f3755dc9d6a81f635a57c52b1928093373849ff047c6b1b320cadaf88588133c8c7e0e5b4eed16dc965700c21990db8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
